[package]
name = "onnx_inference"
version = "0.1.0"
edition = "2024"

[lib]
name = "onnx_inference"
crate-type = ["cdylib"]

[dependencies]
ort = { version = "2.0.0-rc.10", default-features = false, features = ["load-dynamic"] }
image = "0.24"
ndarray = "0.15"
jni = "0.21"
libc = "0.2"
