[env]
ORT_STRATEGY = "system"
ORT_USE_STATIC = "1"

[target.aarch64-linux-android]
linker = "aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android-clang"